name: Build and deploy ASP.Net Core app to Azure Web App - api-versopay-dev2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore ./VersopayBackend/VersopayBackend.csproj

      - name: Build (Release)
        run: dotnet build ./VersopayBackend/VersopayBackend.csproj -c Release --no-restore

      - name: Publish (Release)
        run: dotnet publish ./VersopayBackend/VersopayBackend.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1) CÃ³digo-fonte para migrations
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # 2) EF Core migrations (antes do deploy)
      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        shell: pwsh
        run: echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH

      - name: Run EF Core Migrations
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DEV_SQL_CONNECTION_STRING }}
          ASPNETCORE_ENVIRONMENT: Development
        run: |
          dotnet ef database update `
            --project ./VersopayDatabase/VersopayDatabase.csproj `
            --startup-project ./VersopayBackend/VersopayBackend.csproj `
            --context AppDbContext

      # 3) Baixa o build publicado (depois do checkout, em pasta separada)
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./artifact
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C65A5CBEF697494D8CCA93C3C9D174B4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21694DD3A2154C4988CC215453AD9F62 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA6A44D993B349BA83AFD9D4BA8A7360 }}

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D62FADCD9F5547BAAE0703EE096799B9 }}

      # 5) Deploy do pacote publicado
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-versopay-dev2'
          slot-name: 'Production'
          package: ./artifact
